services:
  mongodb:
    image: mongo:7
    container_name: makia-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: makia_dev
    volumes:
      - makia_mongo_data:/data/db

volumes:
  makia_mongo_data:
